routes/dashboard.php
<?php

use App\Http\Controllers\Dashboard\Articles\ArticlesController;
use App\Http\Controllers\Dashboard\Auth\LoginController;
use App\Http\Controllers\Dashboard\Categories\CategoriesController;
use App\Http\Controllers\Dashboard\Users\UsersController;
use App\Http\Controllers\Dashboard\Visitors\VisitorsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Dashboard Routes
|--------------------------------------------------------------------------
|
| Here is where you can register dashboard routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

# Login routes.
Route::get('login', [LoginController::class, 'showLoginForm'])->name('admin.login');
Route::post('login', [LoginController::class, 'login'])->name('admin.login');
Route::any('logout', [LoginController::class, 'logout'])->name('admin.logout');

# Dashboard group routes.
Route::group(['middleware' => ['auth']], function () {

    # Dashboard route.
    Route::get('/', function () {
        return view('dashboard.home.home');
    })->name('admin.home');

    # Users routes.
    Route::resource('users', UsersController::class)->except('show');
    Route::put('users/update/password/{user}', [UsersController::class, 'updatePassword'])->name('user.update.password');

    # Visitors routes.
    Route::resource('visitors', VisitorsController::class)->except('show');
    Route::put('visitors/update/password/{visitor}', [VisitorsController::class, 'updatePassword'])->name('visitor.update.password');

    # Articles routes.
    Route::resource('articles', ArticlesController::class)->except('show');

    # Categories routes.
    Route::resource('categories', CategoriesController::class)->except('show');
});

routes/web.php
<?php

use App\Http\Controllers\Frontend\Articles\ArticlesController;
use App\Http\Controllers\Frontend\Auth\LoginController;
use App\Http\Controllers\Frontend\Auth\RegisterController;
use App\Http\Controllers\Frontend\Comments\CommentsController;
use App\Http\Controllers\Frontend\Home\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

# BEGIN :: login routes.
Route::get('login', [LoginController::class, 'showLoginForm'])->name('front.login');
Route::post('login', [LoginController::class, 'login']);

Route::get('register', [RegisterController::class, 'showRegistrationForm'])->name('front.register');
Route::post('register', [RegisterController::class, 'register']);
Route::any('logout', [LoginController::class, 'logout'])->name('front.logout');

Route::get('/', [HomeController::class, 'index'])->name('front.home');

# Article routes.
Route::get('article/{article}/{slug}', [ArticlesController::class, 'show'])->name('front.article');

Route::group(['middleware' => 'auth:visitor'], function (){
    Route::post('comment/{article}', [CommentsController::class, 'store'])->name('front.comments.store');
});

app/Models/Article.php
<?php

namespace App\Models;

use App\Enums\GeneralEnums;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Str;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Article extends Model implements HasMedia
{
    use HasFactory, InteractsWithMedia;

    protected $appends = ['article_image'];

    protected $fillable = [
        'title',
        'description',
        'body',
        'category_id',
        'status' # 1 => DISABLED | 2 => ACTIVE.
    ];

    /**
     * Return article image.
     *
     * @return string $imagePath
     */
    public function getArticleImageAttribute(): string
    {
        if ($image = $this->getFirstMediaUrl('article_image')) {
            return $image;
        }

        return Url(GeneralEnums::DEFAULT_IMAGE_PLACEHOLDER);
    }

    /**
     * Get status details.
     *
     * @return string[]
     */
    public function getStatusNameAttribute(): array
    {
        return $this->status == 1 ? ['name' => 'Disabled', 'class' => 'warning'] : ['name' => 'Active', 'class' => 'success'];
    }

    /**
     * Category relation.
     *
     * @return BelongsTo
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * Comments relation.
     *
     * @return HasMany
     */
    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class)->with('visitor');
    }

    /**
     * Get article slug.
     *
     * @return string
     */
    public function getSlugNameAttribute(): string
    {
        return Str::slug($this->title);
    }
}

app/Http/Controllers/Dashboard/Articles/ArticlesController.php
<?php

namespace App\Http\Controllers\Dashboard\Articles;

use App\Http\Controllers\Controller;
use App\Http\Requests\Articles\ArticleStoreRequest;
use App\Http\Requests\Articles\ArticleUpdateRequest;
use App\Models\Article;
use App\Repositories\Articles\ArticlesRepositories;
use App\Repositories\Categories\CategoriesRepository;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Redirector;

class ArticlesController extends Controller
{
    protected $model;
    protected $categoriesRepository;

    public function __construct(ArticlesRepositories $articlesRepositories, CategoriesRepository $categoriesRepository)
    {
        $this->model = $articlesRepositories;
        $this->categoriesRepository = $categoriesRepository;
    }

    /**
     * Display a listing of the articles.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        # List articles.
        $articles = $this->model->get();

        return view('dashboard.articles.index', compact('articles'));
    }

    /**
     * Show the form for creating a new article.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        # Repository to list categories.
        $categories = $this->categoriesRepository->list();

        return view('dashboard.articles.create', compact('categories'));
    }

    /**
     * Store a newly created article in storage.
     *
     * @param ArticleStoreRequest $request
     * @return Application|RedirectResponse|Redirector
     */
    public function store(ArticleStoreRequest $request)
    {
        # check if repository not create article return alert.
        if( !$this->model->create( array_merge($request->except('_token', 'after'), ['user_id' => auth()->user()->id]) ) )
            return redirect()->back()->with('warning', __('messages.field_process'));

        # check if submit on btn create & new
        if ($request->get('after') == 'new'){
            return redirect()->route('articles.create')->with('success', __('system.created'));
        }

        return redirect()->route('articles.index')->with('success', __('system.created'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified article.
     *
     * @param Article $article
     * @return Application|Factory|View
     */
    public function edit(Article $article)
    {
        # Repository to list categories.
        $categories = $this->categoriesRepository->list();

        return view('dashboard.articles.edit', compact('article', 'categories'));
    }

    /**
     * Update the specified article in storage.
     *
     * @param Article $article
     * @param Request $request
     * @param $id
     * @return Application|RedirectResponse|Redirector
     */
    public function update(ArticleUpdateRequest $request, Article $article)
    {
        # check if repository not update article return alert.
        if( !$this->model->update($article, $request->except('_token', '_method')) )
            return redirect()->back()->with('warning', __('messages.field_process'));

        return redirect()->route('articles.index', $article->id)->with('success', __('system.updated'));
    }

    /**
     * Remove the specified article from storage.
     *
     * @param Article $article
     * @return Application|RedirectResponse|Redirector
     */
    public function destroy(Article $article)
    {
        # check if repository not delete article return alert.
        if( !$this->model->delete($article) )
            return redirect()->back()->with('warning', __('messages.field_process'));

        return redirect()->route('articles.index')->with('success', __('system.deleted'));
    }
}

app/Http/Controllers/Dashboard/Categories/CategoriesController.php
<?php

namespace App\Http\Controllers\Dashboard\Categories;

use App\Http\Controllers\Controller;
use App\Http\Requests\Categories\CategoryStoreRequest;
use App\Http\Requests\Categories\CategoryUpdateRequest;
use App\Models\Category;
use App\Repositories\Categories\CategoriesRepository;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\Redirector;

class CategoriesController extends Controller
{
    protected $model;

    /**
     * CategoriesRepository constructor.
     *
     * @param CategoriesRepository $categoriesRepository
     */
    public function __construct(CategoriesRepository $categoriesRepository)
    {
        $this->model = $categoriesRepository;
    }

    /**
     * Display a listing of the categories.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        # List categories.
        $categories = $this->model->get();

        return view('dashboard.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new category.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('dashboard.categories.create');
    }

    /**
     * Store a newly created category in storage.
     *
     * @param CategoryStoreRequest $request
     *
     * @return Application|RedirectResponse|Redirector
     */
    public function store(CategoryStoreRequest $request)
    {
        # check if repository not create category return alert.
        if( !$this->model->create( $request->except('_token', 'after') ) )
            return redirect()->back()->with('failed', __('messages.field_process'));

        # check if submit on btn create & new
        if ($request->get('after') == 'new')
            return redirect()->route('categories.create')->with('success', __('system.created'));

        return redirect()->route('categories.index')->with('success', __('system.created'));
    }

    /**
     * Display the specified specific.
     *
     * @param int $id
     */
    public function show(int $id)
    {
        //
    }

    /**
     * Show the form for editing the specified category.
     *
     * @param Category $category
     * @return Application|Factory|View
     */
    public function edit(Category $category)
    {
        return view('dashboard.categories.edit', compact('category'));
    }

    /**
     * Update the specified category in storage.
     *
     * @param Category $category
     * @param CategoryUpdateRequest $request
     * @return Application|RedirectResponse|Redirector
     */
    public function update(CategoryUpdateRequest $request, Category $category)
    {
        # check if repository not update category return alert.
        if( !$this->model->update($category, $request->except('_token', '_method')) )
            return redirect()->back()->with('failed', __('messages.field_process'));

        return redirect()->back()->with('success', __('system.updated'));
    }

    /**
     * Remove the specified category from storage.
     *
     * @param Category $category
     * @return Application|RedirectResponse|Redirector
     * @throws \Exception
     */
    public function destroy(Category $category)
    {
        # check if repository not delete category return alert.
        if( !$this->model->delete($category) )
            return redirect()->back()->with('failed', __('messages.field_process'));

        return redirect()->back()->with('success', __('system.deleted'));
    }
}

app/Http/Controllers/Dashboard/Comments/CommentsController.php
<?php

namespace App\Http\Controllers\Dashboard\Comments;

use App\Http\Controllers\Controller;
use App\Http\Requests\Comments\CommentStoreRequest;
use App\Http\Requests\Comments\CommentUpdateRequest;
use App\Models\Comment;
use App\Repositories\Comments\CommentRepository;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class CommentsController extends Controller
{
    protected $commentsRepository;

    /**
     * Comment Repository constructor.
     *
     * @param CommentRepository $commentsRepository
     */
    public function __construct(CommentRepository $commentsRepository)
    {
        $this->commentsRepository = $commentsRepository;
    }

    /**
     * Display a listing of the comments.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        # List comments.
        $comments = $this->commentsRepository->get();

        return view('dashboard.comments.index', compact('comments'));
    }

    /**
     * Show the form for creating a new comment.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        return view('dashboard.comments.create');
    }

    /**
     * Store a newly created comment in storage.
     *
     * @param CommentStoreRequest $request
     * @return RedirectResponse
     */
    public function store(CommentStoreRequest $request)
    {
        # check if repository not create comment return alert.
        if( !$this->commentsRepository->create( $request->except('_token', 'after') ) )
            return redirect()->back()->with('warning', __('messages.field_process'));

        # check if submit on btn create & new
        if ($request->get('after') == 'new'){
            return redirect()->route('comments.create')->with('success', __('system.created'));
        }

        return redirect()->route('comments.index')->with('success', __('system.created'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified comment.
     *
     * @param Comment $comment
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit(Comment $comment)
    {
        return view('dashboard.comments.edit', compact('comment'));
    }

    /**
     * Update the specified comment in storage.
     *
     * @param CommentUpdateRequest $request
     *
     * @param Comment $comment
     *
     * @return RedirectResponse
     */
    public function update(CommentUpdateRequest $request, Comment $comment)
    {
        # check if repository not update comment return alert.
        if( !$this->commentsRepository->update($comment, $request->except('_token', '_method')) )
            return redirect()->back()->with('warning', __('messages.field_process'));

        return redirect()->route('comments.index')->with('success', __('system.updated'));
    }

    /**
     * Remove the specified comment from storage.
     *
     * @param Comment $comment
     *
     * @return RedirectResponse
     */
    public function destroy(Comment $comment)
    {
        # check if repository not delete board return alert.
        if( !$this->commentsRepository->delete($comment) )
            return redirect()->back()->with('warning', __('messages.field_process'));

        return redirect()->route('comments.index')->with('success', __('system.deleted'));
    }
}

app/Http/Controllers/Frontend/Articles/ArticlesController.php
<?php

namespace App\Http\Controllers\Frontend\Articles;

use App\Http\Controllers\Controller;
use App\Models\Article;
use App\Repositories\Articles\ArticlesRepositories;
use App\Repositories\Categories\CategoriesRepository;
use Illuminate\Http\Request;

class ArticlesController extends Controller
{
    /**
     * Get page to display articles details.
     *
     * @param Article $article
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function show(Article $article, $slug)
    {
        # Repository to list categories.
        $categories = app(CategoriesRepository::class)->list();

        return view('frontend.articles.show', compact('article', 'categories'));
    }
}

resources/views/dashboard/articles/create.blade.php
@extends('dashboard.layouts.master')

@section('title', __('system.create-article'))

@push('styles')
    <link rel="stylesheet" href="{{ asset('assets/dashboard/custom/dropify/dist/css/dropify.min.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
@endpush

@section('content')

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Create Article</h1>

    <!-- BEGIN :: include alert error section -->
    @include('dashboard.components.alert.failed-alert')
    <!-- END :: include alert error section -->

    <!-- BEGIN :: include alert error section -->
    @include('dashboard.components.alert.warning-alert')
    <!-- END :: include alert error section -->

    <!-- BEGIN :: include alert success section -->
    @include('dashboard.components.alert.success-alert')
    <!-- END :: include alert success section -->

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Create Article</h6>
        </div>

        <div class="card-body">
            <form class="form" method="post" action="{{ route('articles.store') }}" enctype="multipart/form-data">
                @csrf

                <!-- BEGIN :: include admin details section -->
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="phone">@lang('system.image')</label>

                                <input type="file"
                                       name="article_image"
                                       id="input-file-now-custom-1"
                                       class="dropify @error('article_image') is-invalid @enderror" />

                                @error('article_image')
                                    <small class="help-block text-danger"> {{ $message }} </small>
                                @enderror
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="title">Category</label>
                                <select class="form-select form-control" aria-label="Default select example" name="category_id">
                                    <option value="">-- Choose --</option>
                                    @foreach($categories as $category)
                                        <option value="{{ $category->id }}" {{ old('category_id') == $category->id ? 'selected' : ''}}>
                                            {{ $category->name }}
                                        </option>
                                    @endforeach
                                </select>

                                @error('category_id')
                                    <div class="help-block text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="title">@lang('system.title')</label>

                                <input type="text"
                                       name="title"
                                       placeholder="@lang('system.title')"
                                       id="title"
                                       value="{{ old('title') }}"
                                       class="form-control @error('title') is-invalid @enderror" />

                                @error('title')
                                    <div class="help-block text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="title">@lang('system.description')</label>

                                <input type="text"
                                       name="description"
                                       placeholder="@lang('system.description')"
                                       id="title"
                                       value="{{ old('description') }}"
                                       class="form-control @error('title') is-invalid @enderror" />

                                @error('description')
                                    <div class="help-block text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="title">@lang('system.body')</label>

                                <textarea name="body"
                                          id="summernote"
                                          class="form-control @error('body') is-invalid @enderror">{{ old('body') }}</textarea>

                                @error('body')
                                    <div class="help-block text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>

                        <div class="col-md-12 form-group">
                            <label for="title">Status</label>

                            <div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input"
                                           type="radio"
                                           name="status"
                                           id="inlineRadio1"
                                           value="1" checked />
                                    <label class="form-check-label" for="inlineRadio1">Disabled</label>
                                </div>

                                <div class="form-check form-check-inline">
                                    <input class="form-check-input"
                                           type="radio"
                                           name="status"
                                           id="inlineRadio2"
                                           value="2" {{ old('status') == 2 ? 'checked' : '' }} />

                                    <label class="form-check-label" for="inlineRadio2">Active</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- BEGIN :: include create btn group section -->
                @include('dashboard.components.btn.create-btn-group',['url' => route("articles.index")])
                <!-- END :: include create btn group section -->
            </form>
        </div>
    </div>
    <!-- END : End Main Content-->
@stop

@push('js')
    <script src="{{ asset('assets/dashboard/custom/dropify/dist/js/dropify.min.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>

    <script>
        $(document).ready(function() {
            // Basic
            $('.dropify').dropify();

            $('#summernote').summernote({
                placeholder: '{{ __('system.body') }}',
                tabsize: 2,
                height: 250,
            });
        });
    </script>
@endpush

resources/views/dashboard/articles/index.blade.php
@extends('dashboard.layouts.master')

@section('title', __('system.articles'))

@section('content')
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Articles</h1>

    <!-- BEGIN :: include alert error section -->
    @include('dashboard.components.alert.failed-alert')
    <!-- END :: include alert error section -->

    <!-- BEGIN :: include alert error section -->
    @include('dashboard.components.alert.warning-alert')
    <!-- END :: include alert error section -->

    <!-- BEGIN :: include alert success section -->
    @include('dashboard.components.alert.success-alert')
    <!-- END :: include alert success section -->

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Articles</h6>

            <a class="btn btn-raised btn-info btn-min-width mr-1 mb-1 float-right" href="{{ route('articles.create')  }}">
                <i class="fa fa-plus"></i>
                @lang('system.create-new')
            </a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th class="text-center">#ID</th>
                        <th class="text-center">Image</th>
                        <th class="text-center">Category</th>
                        <th class="text-center">Name</th>
                        <th class="text-center">Status</th>
                        <th class="text-center">Tools</th>
                    </tr>
                    </thead>
                    <tbody>
                        @forelse($articles as $article)
                            <tr>
                                <td class="text-center">{{ $article->id }}</td>
                                <td class="text-center">
                                    <img class="media-object round-media" src="{{ $article->articleImage }}" alt="{{ $article->title }}" style="height: 50px;width: 75px">
                                </td>
                                <td class="text-center">{{ $article->category->name }}</td>
                                <td class="text-center">{{ $article->title }}</td>
                                <td class="text-center">
                                    <button class="btn btn-{{  $article->statusName['class'] }}">
                                        {{  $article->statusName['name'] }}
                                    </button>
                                </td>
                                <td class="text-center">
                                    <a href="{{ route('articles.edit', $article->id) }}"
                                       class="btn btn-raised btn-info btn-min-width mr-1">
                                        <i class="far fa-edit"></i>
                                    </a>

                                    <!-- BEGIN :: include delete btn -->
                                    @include('dashboard.components.btn.delete-btn', [
                                        'modal_target' => '#delete-article-modal',
                                        'name' => $article->name,
                                        'url' => route('articles.destroy',$article->id),
                                        'btn_id' => 'delete-article'
                                    ])
                                    <!-- END :: include delete btn -->
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td></td>
                                <td class="text-center" colspan="2"> @lang('messages.there_are_no_data') </td>
                                <td></td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- END : End Main Content-->

    <!-- Begin : include delete modal -->
    @include('dashboard.components.modals.delete-modal', [
        'modal_id' => 'delete-article-modal',
        'form_id' => 'delete-article-form',
        'delete_title' => __('system.article'),
        'btn_delete_id' => '#delete-article'
    ])
    <!-- End : include delete modal -->
@stop