routes/dashboard.php
<?php

use App\Http\Controllers\Dashboard\Articles\ArticlesController;
use App\Http\Controllers\Dashboard\Auth\LoginController;
use App\Http\Controllers\Dashboard\Categories\CategoriesController;
use App\Http\Controllers\Dashboard\Users\UsersController;
use App\Http\Controllers\Dashboard\Visitors\VisitorsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Dashboard Routes
|--------------------------------------------------------------------------
|
| Here is where you can register dashboard routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

# Login routes.
Route::get('login', [LoginController::class, 'showLoginForm'])->name('admin.login');
Route::post('login', [LoginController::class, 'login'])->name('admin.login');
Route::any('logout', [LoginController::class, 'logout'])->name('admin.logout');

# Dashboard group routes.
Route::group(['middleware' => ['auth']], function () {

    # Dashboard route.
    Route::get('/', function () {
        return view('dashboard.home.home');
    })->name('admin.home');

    # Users routes.
    Route::resource('users', UsersController::class)->except('show');
    Route::put('users/update/password/{user}', [UsersController::class, 'updatePassword'])->name('user.update.password');

    # Visitors routes.
    Route::resource('visitors', VisitorsController::class)->except('show');
    Route::put('visitors/update/password/{visitor}', [VisitorsController::class, 'updatePassword'])->name('visitor.update.password');

    # Articles routes.
    Route::resource('articles', ArticlesController::class)->except('show');

    # Categories routes.
    Route::resource('categories', CategoriesController::class)->except('show');
});

routes/web.php
<?php

use App\Http\Controllers\Frontend\Articles\ArticlesController;
use App\Http\Controllers\Frontend\Auth\LoginController;
use App\Http\Controllers\Frontend\Auth\RegisterController;
use App\Http\Controllers\Frontend\Comments\CommentsController;
use App\Http\Controllers\Frontend\Home\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

# BEGIN :: login routes.
Route::get('login', [LoginController::class, 'showLoginForm'])->name('front.login');
Route::post('login', [LoginController::class, 'login']);

Route::get('register', [RegisterController::class, 'showRegistrationForm'])->name('front.register');
Route::post('register', [RegisterController::class, 'register']);
Route::any('logout', [LoginController::class, 'logout'])->name('front.logout');

Route::get('/', [HomeController::class, 'index'])->name('front.home');

# Article routes.
Route::get('article/{article}/{slug}', [ArticlesController::class, 'show'])->name('front.article');

Route::group(['middleware' => 'auth:visitor'], function (){
    Route::post('comment/{article}', [CommentsController::class, 'store'])->name('front.comments.store');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Category extends Model
{
    protected $fillable = ['name'];

    /**
     * Articles relation.
     *
     * @return HasMany
     */
    public function articles(): HasMany
    {
        return $this->hasMany(Article::class);
    }
}

app/Http/Controllers/Dashboard/Articles/ArticlesController.php
<?php

namespace App\Http\Controllers\Dashboard\Articles;

use App\Http\Controllers\Controller;
use App\Http\Requests\Articles\ArticleStoreRequest;
use App\Http\Requests\Articles\ArticleUpdateRequest;
use App\Models\Article;
use App\Repositories\Articles\ArticlesRepositories;
use App\Repositories\Categories\CategoriesRepository;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Redirector;

class ArticlesController extends Controller
{
    protected $model;
    protected $categoriesRepository;

    public function __construct(ArticlesRepositories $articlesRepositories, CategoriesRepository $categoriesRepository)
    {
        $this->model = $articlesRepositories;
        $this->categoriesRepository = $categoriesRepository;
    }

    /**
     * Display a listing of the articles.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        # List articles.
        $articles = $this->model->get();

        return view('dashboard.articles.index', compact('articles'));
    }

    /**
     * Show the form for creating a new article.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        # Repository to list categories.
        $categories = $this->categoriesRepository->list();

        return view('dashboard.articles.create', compact('categories'));
    }

    /**
     * Store a newly created article in storage.
     *
     * @param ArticleStoreRequest $request
     * @return Application|RedirectResponse|Redirector
     */
    public function store(ArticleStoreRequest $request)
    {
        # check if repository not create article return alert.
        if( !$this->model->create( array_merge($request->except('_token', 'after'), ['user_id' => auth()->user()->id]) ) )
            return redirect()->back()->with('warning', __('messages.field_process'));

        # check if submit on btn create & new
        if ($request->get('after') == 'new'){
            return redirect()->route('articles.create')->with('success', __('system.created'));
        }

        return redirect()->route('articles.index')->with('success', __('system.created'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified article.
     *
     * @param Article $article
     * @return Application|Factory|View
     */
    public function edit(Article $article)
    {
        # Repository to list categories.
        $categories = $this->categoriesRepository->list();

        return view('dashboard.articles.edit', compact('article', 'categories'));
    }

    /**
     * Update the specified article in storage.
     *
     * @param Article $article
     * @param Request $request
     * @param $id
     * @return Application|RedirectResponse|Redirector
     */
    public function update(ArticleUpdateRequest $request, Article $article)
    {
        # check if repository not update article return alert.
        if( !$this->model->update($article, $request->except('_token', '_method')) )
            return redirect()->back()->with('warning', __('messages.field_process'));

        return redirect()->route('articles.index', $article->id)->with('success', __('system.updated'));
    }

    /**
     * Remove the specified article from storage.
     *
     * @param Article $article
     * @return Application|RedirectResponse|Redirector
     */
    public function destroy(Article $article)
    {
        # check if repository not delete article return alert.
        if( !$this->model->delete($article) )
            return redirect()->back()->with('warning', __('messages.field_process'));

        return redirect()->route('articles.index')->with('success', __('system.deleted'));
    }
}

app/Http/Controllers/Dashboard/Categories/CategoriesController.php
<?php

namespace App\Http\Controllers\Dashboard\Categories;

use App\Http\Controllers\Controller;
use App\Http\Requests\Categories\CategoryStoreRequest;
use App\Http\Requests\Categories\CategoryUpdateRequest;
use App\Models\Category;
use App\Repositories\Categories\CategoriesRepository;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\Redirector;

class CategoriesController extends Controller
{
    protected $model;

    /**
     * CategoriesRepository constructor.
     *
     * @param CategoriesRepository $categoriesRepository
     */
    public function __construct(CategoriesRepository $categoriesRepository)
    {
        $this->model = $categoriesRepository;
    }

    /**
     * Display a listing of the categories.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        # List categories.
        $categories = $this->model->get();

        return view('dashboard.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new category.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('dashboard.categories.create');
    }

    /**
     * Store a newly created category in storage.
     *
     * @param CategoryStoreRequest $request
     *
     * @return Application|RedirectResponse|Redirector
     */
    public function store(CategoryStoreRequest $request)
    {
        # check if repository not create category return alert.
        if( !$this->model->create( $request->except('_token', 'after') ) )
            return redirect()->back()->with('failed', __('messages.field_process'));

        # check if submit on btn create & new
        if ($request->get('after') == 'new')
            return redirect()->route('categories.create')->with('success', __('system.created'));

        return redirect()->route('categories.index')->with('success', __('system.created'));
    }

    /**
     * Display the specified specific.
     *
     * @param int $id
     */
    public function show(int $id)
    {
        //
    }

    /**
     * Show the form for editing the specified category.
     *
     * @param Category $category
     * @return Application|Factory|View
     */
    public function edit(Category $category)
    {
        return view('dashboard.categories.edit', compact('category'));
    }

    /**
     * Update the specified category in storage.
     *
     * @param Category $category
     * @param CategoryUpdateRequest $request
     * @return Application|RedirectResponse|Redirector
     */
    public function update(CategoryUpdateRequest $request, Category $category)
    {
        # check if repository not update category return alert.
        if( !$this->model->update($category, $request->except('_token', '_method')) )
            return redirect()->back()->with('failed', __('messages.field_process'));

        return redirect()->back()->with('success', __('system.updated'));
    }

    /**
     * Remove the specified category from storage.
     *
     * @param Category $category
     * @return Application|RedirectResponse|Redirector
     * @throws \Exception
     */
    public function destroy(Category $category)
    {
        # check if repository not delete category return alert.
        if( !$this->model->delete($category) )
            return redirect()->back()->with('failed', __('messages.field_process'));

        return redirect()->back()->with('success', __('system.deleted'));
    }
}

app/Http/Controllers/Dashboard/Comments/CommentsController.php
<?php

namespace App\Http\Controllers\Dashboard\Comments;

use App\Http\Controllers\Controller;
use App\Http\Requests\Comments\CommentStoreRequest;
use App\Http\Requests\Comments\CommentUpdateRequest;
use App\Models\Comment;
use App\Repositories\Comments\CommentRepository;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class CommentsController extends Controller
{
    protected $commentsRepository;

    /**
     * Comment Repository constructor.
     *
     * @param CommentRepository $commentsRepository
     */
    public function __construct(CommentRepository $commentsRepository)
    {
        $this->commentsRepository = $commentsRepository;
    }

    /**
     * Display a listing of the comments.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        # List comments.
        $comments = $this->commentsRepository->get();

        return view('dashboard.comments.index', compact('comments'));
    }

    /**
     * Show the form for creating a new comment.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        return view('dashboard.comments.create');
    }

    /**
     * Store a newly created comment in storage.
     *
     * @param CommentStoreRequest $request
     * @return RedirectResponse
     */
    public function store(CommentStoreRequest $request)
    {
        # check if repository not create comment return alert.
        if( !$this->commentsRepository->create( $request->except('_token', 'after') ) )
            return redirect()->back()->with('warning', __('messages.field_process'));

        # check if submit on btn create & new
        if ($request->get('after') == 'new'){
            return redirect()->route('comments.create')->with('success', __('system.created'));
        }

        return redirect()->route('comments.index')->with('success', __('system.created'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified comment.
     *
     * @param Comment $comment
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit(Comment $comment)
    {
        return view('dashboard.comments.edit', compact('comment'));
    }

    /**
     * Update the specified comment in storage.
     *
     * @param CommentUpdateRequest $request
     *
     * @param Comment $comment
     *
     * @return RedirectResponse
     */
    public function update(CommentUpdateRequest $request, Comment $comment)
    {
        # check if repository not update comment return alert.
        if( !$this->commentsRepository->update($comment, $request->except('_token', '_method')) )
            return redirect()->back()->with('warning', __('messages.field_process'));

        return redirect()->route('comments.index')->with('success', __('system.updated'));
    }

    /**
     * Remove the specified comment from storage.
     *
     * @param Comment $comment
     *
     * @return RedirectResponse
     */
    public function destroy(Comment $comment)
    {
        # check if repository not delete board return alert.
        if( !$this->commentsRepository->delete($comment) )
            return redirect()->back()->with('warning', __('messages.field_process'));

        return redirect()->route('comments.index')->with('success', __('system.deleted'));
    }
}

resources/views/dashboard/categories/create.blade.php
@extends('dashboard.layouts.master')

@section('title', 'Create Category')

@section('content')

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Create Category</h1>

    <!-- BEGIN :: include alert error section -->
    @include('dashboard.components.alert.failed-alert')
    <!-- END :: include alert error section -->

    <!-- BEGIN :: include alert error section -->
    @include('dashboard.components.alert.warning-alert')
    <!-- END :: include alert error section -->

    <!-- BEGIN :: include alert success section -->
    @include('dashboard.components.alert.success-alert')
    <!-- END :: include alert success section -->

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Create Category</h6>
        </div>

        <div class="card-body">
            <form class="form" method="post" action="{{ route('categories.store') }}">
                @csrf

                <!-- BEGIN :: include admin details section -->
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="name">Name</label>

                                <input type="text"
                                       name="name"
                                       placeholder="Name"
                                       id="name"
                                       value="{{ old('name') }}"
                                       class="form-control @error('name') is-invalid @enderror" />

                                @error('name')
                                    <div class="help-block text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                    </div>
                </div>

                <!-- BEGIN :: include create btn group section -->
                @include('dashboard.components.btn.create-btn-group',['url' => route("categories.index")])
                <!-- END :: include create btn group section -->
            </form>
        </div>
    </div>
    <!-- END : End Main Content-->
@stop

resources/views/dashboard/categories/edit.blade.php
@extends('dashboard.layouts.master')

@section('title', 'Edit Article')

@section('content')
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Edit Category</h1>

    <!-- BEGIN :: include alert error section -->
    @include('dashboard.components.alert.failed-alert')
    <!-- END :: include alert error section -->

    <!-- BEGIN :: include alert error section -->
    @include('dashboard.components.alert.warning-alert')
    <!-- END :: include alert error section -->

    <!-- BEGIN :: include alert success section -->
    @include('dashboard.components.alert.success-alert')
    <!-- END :: include alert success section -->

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Create Category</h6>
        </div>
        <div class="card-body">
            <form class="form" method="post" action="{{ route('categories.update', $category->id) }}">
                @csrf
                @method('PUT')

            <!-- BEGIN :: include admin details section -->
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="name">Name</label>

                                <input type="text"
                                       name="name"
                                       placeholder="Name"
                                       id="name"
                                       value="{{ $category->name }}"
                                       class="form-control @error('name') is-invalid @enderror" />

                                @error('name')
                                    <div class="help-block text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                    </div>
                </div>

                <!-- BEGIN :: include create btn group section -->
                @include('dashboard.components.btn.edit-btn-group',['url' => route("categories.index")])
                <!-- END :: include create btn group section -->
            </form>
        </div>
    </div>
    <!-- END : End Main Content-->
@stop

resources/views/dashboard/categories/index.blade.php
@extends('dashboard.layouts.master')

@section('title', 'Categories')

@section('content')
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Categories</h1>

    <!-- BEGIN :: include alert error section -->
    @include('dashboard.components.alert.failed-alert')
    <!-- END :: include alert error section -->

    <!-- BEGIN :: include alert error section -->
    @include('dashboard.components.alert.warning-alert')
    <!-- END :: include alert error section -->

    <!-- BEGIN :: include alert success section -->
    @include('dashboard.components.alert.success-alert')
    <!-- END :: include alert success section -->

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Categories</h6>

            <a class="btn btn-raised btn-info btn-min-width mr-1 mb-1 float-right" href="{{ route('categories.create')  }}">
                <i class="fa fa-plus"></i>
                @lang('system.create-new')
            </a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th class="text-center">#ID</th>
                        <th class="text-center">name</th>
                        <th class="text-center">Tools</th>
                    </tr>
                    </thead>
                    <tbody>
                        @forelse($categories as $category)
                            <tr>
                                <td class="text-center">{{ $category->id }}</td>
                                <td class="text-center">{{ $category->name }}</td>
                                <td class="text-center">
                                    <a href="{{ route('categories.edit', $category->id) }}"
                                       class="btn btn-raised btn-info btn-min-width mr-1">
                                        <i class="far fa-edit"></i>
                                    </a>

                                    <!-- BEGIN :: include delete btn -->
                                    @include('dashboard.components.btn.delete-btn', [
                                        'modal_target' => '#delete-category-modal',
                                        'name' => $category->name,
                                        'url' => route('categories.destroy', $category->id),
                                        'btn_id' => 'delete-category'
                                    ])
                                    <!-- END :: include delete btn -->
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td></td>
                                <td class="text-center"> @lang('messages.there_are_no_data') </td>
                                <td></td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- END : End Main Content-->

    <!-- Begin : include delete modal -->
    @include('dashboard.components.modals.delete-modal', [
        'modal_id' => 'delete-category-modal',
        'form_id' => 'delete-category-form',
        'delete_title' => 'Category',
        'btn_delete_id' => '#delete-category'
    ])
    <!-- End : include delete modal -->
@stop