routes/dashboard.php
<?php

use App\Http\Controllers\Dashboard\Articles\ArticlesController;
use App\Http\Controllers\Dashboard\Auth\LoginController;
use App\Http\Controllers\Dashboard\Categories\CategoriesController;
use App\Http\Controllers\Dashboard\Users\UsersController;
use App\Http\Controllers\Dashboard\Visitors\VisitorsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Dashboard Routes
|--------------------------------------------------------------------------
|
| Here is where you can register dashboard routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

# Login routes.
Route::get('login', [LoginController::class, 'showLoginForm'])->name('admin.login');
Route::post('login', [LoginController::class, 'login'])->name('admin.login');
Route::any('logout', [LoginController::class, 'logout'])->name('admin.logout');

# Dashboard group routes.
Route::group(['middleware' => ['auth']], function () {

    # Dashboard route.
    Route::get('/', function () {
        return view('dashboard.home.home');
    })->name('admin.home');

    # Users routes.
    Route::resource('users', UsersController::class)->except('show');
    Route::put('users/update/password/{user}', [UsersController::class, 'updatePassword'])->name('user.update.password');

    # Visitors routes.
    Route::resource('visitors', VisitorsController::class)->except('show');
    Route::put('visitors/update/password/{visitor}', [VisitorsController::class, 'updatePassword'])->name('visitor.update.password');

    # Articles routes.
    Route::resource('articles', ArticlesController::class)->except('show');

    # Categories routes.
    Route::resource('categories', CategoriesController::class)->except('show');
});

routes/web.php
<?php

use App\Http\Controllers\Frontend\Articles\ArticlesController;
use App\Http\Controllers\Frontend\Auth\LoginController;
use App\Http\Controllers\Frontend\Auth\RegisterController;
use App\Http\Controllers\Frontend\Comments\CommentsController;
use App\Http\Controllers\Frontend\Home\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

# BEGIN :: login routes.
Route::get('login', [LoginController::class, 'showLoginForm'])->name('front.login');
Route::post('login', [LoginController::class, 'login']);

Route::get('register', [RegisterController::class, 'showRegistrationForm'])->name('front.register');
Route::post('register', [RegisterController::class, 'register']);
Route::any('logout', [LoginController::class, 'logout'])->name('front.logout');

Route::get('/', [HomeController::class, 'index'])->name('front.home');

# Article routes.
Route::get('article/{article}/{slug}', [ArticlesController::class, 'show'])->name('front.article');

Route::group(['middleware' => 'auth:visitor'], function (){
    Route::post('comment/{article}', [CommentsController::class, 'store'])->name('front.comments.store');
});

app/Models/Visitor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Visitor extends Authenticatable
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'username',
        'phone',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Set password value.
     *
     * @param $value
     */
    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }
}

app/Http/Controllers/Dashboard/Articles/ArticlesController.php
<?php

namespace App\Http\Controllers\Dashboard\Articles;

use App\Http\Controllers\Controller;
use App\Http\Requests\Articles\ArticleStoreRequest;
use App\Http\Requests\Articles\ArticleUpdateRequest;
use App\Models\Article;
use App\Repositories\Articles\ArticlesRepositories;
use App\Repositories\Categories\CategoriesRepository;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Redirector;

class ArticlesController extends Controller
{
    protected $model;
    protected $categoriesRepository;

    public function __construct(ArticlesRepositories $articlesRepositories, CategoriesRepository $categoriesRepository)
    {
        $this->model = $articlesRepositories;
        $this->categoriesRepository = $categoriesRepository;
    }

    /**
     * Display a listing of the articles.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        # List articles.
        $articles = $this->model->get();

        return view('dashboard.articles.index', compact('articles'));
    }

    /**
     * Show the form for creating a new article.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        # Repository to list categories.
        $categories = $this->categoriesRepository->list();

        return view('dashboard.articles.create', compact('categories'));
    }

    /**
     * Store a newly created article in storage.
     *
     * @param ArticleStoreRequest $request
     * @return Application|RedirectResponse|Redirector
     */
    public function store(ArticleStoreRequest $request)
    {
        # check if repository not create article return alert.
        if( !$this->model->create( array_merge($request->except('_token', 'after'), ['user_id' => auth()->user()->id]) ) )
            return redirect()->back()->with('warning', __('messages.field_process'));

        # check if submit on btn create & new
        if ($request->get('after') == 'new'){
            return redirect()->route('articles.create')->with('success', __('system.created'));
        }

        return redirect()->route('articles.index')->with('success', __('system.created'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified article.
     *
     * @param Article $article
     * @return Application|Factory|View
     */
    public function edit(Article $article)
    {
        # Repository to list categories.
        $categories = $this->categoriesRepository->list();

        return view('dashboard.articles.edit', compact('article', 'categories'));
    }

    /**
     * Update the specified article in storage.
     *
     * @param Article $article
     * @param Request $request
     * @param $id
     * @return Application|RedirectResponse|Redirector
     */
    public function update(ArticleUpdateRequest $request, Article $article)
    {
        # check if repository not update article return alert.
        if( !$this->model->update($article, $request->except('_token', '_method')) )
            return redirect()->back()->with('warning', __('messages.field_process'));

        return redirect()->route('articles.index', $article->id)->with('success', __('system.updated'));
    }

    /**
     * Remove the specified article from storage.
     *
     * @param Article $article
     * @return Application|RedirectResponse|Redirector
     */
    public function destroy(Article $article)
    {
        # check if repository not delete article return alert.
        if( !$this->model->delete($article) )
            return redirect()->back()->with('warning', __('messages.field_process'));

        return redirect()->route('articles.index')->with('success', __('system.deleted'));
    }
}

app/Http/Controllers/Dashboard/Categories/CategoriesController.php
<?php

namespace App\Http\Controllers\Dashboard\Categories;

use App\Http\Controllers\Controller;
use App\Http\Requests\Categories\CategoryStoreRequest;
use App\Http\Requests\Categories\CategoryUpdateRequest;
use App\Models\Category;
use App\Repositories\Categories\CategoriesRepository;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\Redirector;

class CategoriesController extends Controller
{
    protected $model;

    /**
     * CategoriesRepository constructor.
     *
     * @param CategoriesRepository $categoriesRepository
     */
    public function __construct(CategoriesRepository $categoriesRepository)
    {
        $this->model = $categoriesRepository;
    }

    /**
     * Display a listing of the categories.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        # List categories.
        $categories = $this->model->get();

        return view('dashboard.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new category.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('dashboard.categories.create');
    }

    /**
     * Store a newly created category in storage.
     *
     * @param CategoryStoreRequest $request
     *
     * @return Application|RedirectResponse|Redirector
     */
    public function store(CategoryStoreRequest $request)
    {
        # check if repository not create category return alert.
        if( !$this->model->create( $request->except('_token', 'after') ) )
            return redirect()->back()->with('failed', __('messages.field_process'));

        # check if submit on btn create & new
        if ($request->get('after') == 'new')
            return redirect()->route('categories.create')->with('success', __('system.created'));

        return redirect()->route('categories.index')->with('success', __('system.created'));
    }

    /**
     * Display the specified specific.
     *
     * @param int $id
     */
    public function show(int $id)
    {
        //
    }

    /**
     * Show the form for editing the specified category.
     *
     * @param Category $category
     * @return Application|Factory|View
     */
    public function edit(Category $category)
    {
        return view('dashboard.categories.edit', compact('category'));
    }

    /**
     * Update the specified category in storage.
     *
     * @param Category $category
     * @param CategoryUpdateRequest $request
     * @return Application|RedirectResponse|Redirector
     */
    public function update(CategoryUpdateRequest $request, Category $category)
    {
        # check if repository not update category return alert.
        if( !$this->model->update($category, $request->except('_token', '_method')) )
            return redirect()->back()->with('failed', __('messages.field_process'));

        return redirect()->back()->with('success', __('system.updated'));
    }

    /**
     * Remove the specified category from storage.
     *
     * @param Category $category
     * @return Application|RedirectResponse|Redirector
     * @throws \Exception
     */
    public function destroy(Category $category)
    {
        # check if repository not delete category return alert.
        if( !$this->model->delete($category) )
            return redirect()->back()->with('failed', __('messages.field_process'));

        return redirect()->back()->with('success', __('system.deleted'));
    }
}

app/Http/Controllers/Dashboard/Comments/CommentsController.php
<?php

namespace App\Http\Controllers\Dashboard\Comments;

use App\Http\Controllers\Controller;
use App\Http\Requests\Comments\CommentStoreRequest;
use App\Http\Requests\Comments\CommentUpdateRequest;
use App\Models\Comment;
use App\Repositories\Comments\CommentRepository;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class CommentsController extends Controller
{
    protected $commentsRepository;

    /**
     * Comment Repository constructor.
     *
     * @param CommentRepository $commentsRepository
     */
    public function __construct(CommentRepository $commentsRepository)
    {
        $this->commentsRepository = $commentsRepository;
    }

    /**
     * Display a listing of the comments.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        # List comments.
        $comments = $this->commentsRepository->get();

        return view('dashboard.comments.index', compact('comments'));
    }

    /**
     * Show the form for creating a new comment.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        return view('dashboard.comments.create');
    }

    /**
     * Store a newly created comment in storage.
     *
     * @param CommentStoreRequest $request
     * @return RedirectResponse
     */
    public function store(CommentStoreRequest $request)
    {
        # check if repository not create comment return alert.
        if( !$this->commentsRepository->create( $request->except('_token', 'after') ) )
            return redirect()->back()->with('warning', __('messages.field_process'));

        # check if submit on btn create & new
        if ($request->get('after') == 'new'){
            return redirect()->route('comments.create')->with('success', __('system.created'));
        }

        return redirect()->route('comments.index')->with('success', __('system.created'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified comment.
     *
     * @param Comment $comment
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit(Comment $comment)
    {
        return view('dashboard.comments.edit', compact('comment'));
    }

    /**
     * Update the specified comment in storage.
     *
     * @param CommentUpdateRequest $request
     *
     * @param Comment $comment
     *
     * @return RedirectResponse
     */
    public function update(CommentUpdateRequest $request, Comment $comment)
    {
        # check if repository not update comment return alert.
        if( !$this->commentsRepository->update($comment, $request->except('_token', '_method')) )
            return redirect()->back()->with('warning', __('messages.field_process'));

        return redirect()->route('comments.index')->with('success', __('system.updated'));
    }

    /**
     * Remove the specified comment from storage.
     *
     * @param Comment $comment
     *
     * @return RedirectResponse
     */
    public function destroy(Comment $comment)
    {
        # check if repository not delete board return alert.
        if( !$this->commentsRepository->delete($comment) )
            return redirect()->back()->with('warning', __('messages.field_process'));

        return redirect()->route('comments.index')->with('success', __('system.deleted'));
    }
}

resources/views/dashboard/visitors/create.blade.php
@extends('dashboard.layouts.master')

@section('title', 'Create Visitor')

@section('content')
    <div class="main-content">
        <div class="content-wrapper">
            <!-- Basic form layout section start -->
            <section id="basic-form-layouts">

                <!-- BEGIN :: include page content header -->
                @include('dashboard.components.pages.content-header', ['title' => 'Create Visitor'])
                <!-- END :: include page content header -->

                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <!-- BEGIN :: include alert error section -->
                                @include('dashboard.components.alert.failed-alert')
                                <!-- END :: include alert error section -->

                                <!-- BEGIN :: include alert error section -->
                                @include('dashboard.components.alert.warning-alert')
                                <!-- END :: include alert error section -->

                                <!-- BEGIN :: include alert success section -->
                                @include('dashboard.components.alert.success-alert')
                                <!-- END :: include alert success section -->
                            </div>

                            <div class="card-content">
                                <div class="px-3">
                                    <form class="form" method="post" action="{{ route('visitors.store') }}">
                                        @csrf

                                        <!-- BEGIN :: include admin details section -->
                                        <div class="form-body">
                                                <h4 class="form-section">
                                                    <i class="fa fa-user"></i>
                                                    Visitor information
                                                </h4>

                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label for="name">@lang('system.name')</label>

                                                            <input type="text"
                                                                   name="name"
                                                                   placeholder="@lang('system.name')"
                                                                   id="name"
                                                                   value="{{ old('name') }}"
                                                                   class="form-control @error('name') is-invalid @enderror" />

                                                            @error('name')
                                                                <div class="help-block text-danger">{{ $message }}</div>
                                                            @enderror
                                                        </div>
                                                    </div>

                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label for="phone">@lang('system.phone')</label>

                                                            <input type="text"
                                                                   name="phone"
                                                                   placeholder="@lang('system.phone')"
                                                                   id="phone"
                                                                   value="{{ old('phone') }}"
                                                                   class="form-control @error('phone') is-invalid @enderror" />

                                                            @error('phone')
                                                                <div class="help-block text-danger">{{ $message }}</div>
                                                            @enderror
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label for="email">@lang('system.email')</label>

                                                            <input type="email"
                                                                   name="email"
                                                                   placeholder="@lang('system.email')"
                                                                   id="email"
                                                                   value="{{ old('email') }}"
                                                                   class="form-control @error('email') is-invalid @enderror" />

                                                            @error('email')
                                                                <div class="help-block text-danger">{{ $message }}</div>
                                                            @enderror
                                                        </div>
                                                    </div>

                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label for="username">@lang('system.username')</label>

                                                            <input type="text"
                                                                   name="username"
                                                                   placeholder="@lang('system.username')"
                                                                   id="username"
                                                                   value="{{ old('username') }}"
                                                                   class="form-control @error('username') is-invalid @enderror" />

                                                            @error('username')
                                                                <div class="help-block text-danger">{{ $message }}</div>
                                                            @enderror
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                        <!-- END :: include admin details section -->

                                        <h4 class="form-section"><i class="fa fa-user-secret"></i> @lang('system.password-data') </h4>

                                        <br/>

                                        <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label for="password">@lang('system.password')</label>

                                                        <input type="password"
                                                               name="password"
                                                               placeholder="@lang('system.password')"
                                                               id="password"
                                                               class="form-control @error('password') is-invalid @enderror" />

                                                        @error('password')
                                                            <div class="help-block text-danger">{{ $message }}</div>
                                                        @enderror
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label for="password_confirmation">@lang('system.password-confirmation')</label>

                                                        <input type="password"
                                                               name="password_confirmation"
                                                               placeholder="@lang('system.password-confirmation')"
                                                               id="password_confirmation"
                                                               class="form-control @error('password_confirmation') is-invalid @enderror" />

                                                        @error('password_confirmation')
                                                            <div class="help-block text-danger">{{ $message }}</div>
                                                        @enderror
                                                    </div>
                                                </div>
                                            </div>

                                        <!-- END :: include admin password section -->

                                        <!-- BEGIN :: include create btn group section -->
                                        @include('dashboard.components.btn.create-btn-group',['url' => route("visitors.index")])
                                        <!-- END :: include create btn group section -->
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- // Basic form layout section end -->
        </div>
    </div>
@endsection